SET NAMES UTF8;
DROP DATABASE IF EXISTS xx;
CREATE DATABASE xx CHARSET=UTF8;
USE xx;

CREATE TABLE xx_user(
    id INT PRIMARY KEY AUTO_INCREMENT,
    pid INT,
    uname VARCHAR(64),
    upwd VARCHAR(64),
    tel VARCHAR(32),
    addr VARCHAR(128)
);
INSERT INTO xx_user VALUES
(1,001,"mike","123","18261197223","北京市")